version: 2.1

jobs:

  build:

    docker:
      - image: circleci/python:3.7.4

    steps:
      - checkout

      - run:
          name: Install Pipenv
          command: sudo pip install pipenv

      - run:
          name: Install Python dependencies
          command: make install

      - run:
          name: Python style check
          command: make check-style

      - run:
          name: Feature tests
          command: make test
