version: 2.1

jobs:

  build:

    docker:
      - image: circleci/python:3.7.4

    steps:
      - checkout

      - run:
          name: Install Pipenv
          command: sudo pip install pipenv

      - run:
          name: Install Python dependencies
          command: make install

      - run:
          name: Python style check
          command: make style-check

      - run:
          name: Type-check with Mypy
          command: |
            python3 -m pip install mypy --user
            make type-check

      - run:
          name: Feature tests
          command: make test
