version: 2.1

jobs:

  build:

    docker:
      - image: circleci/python:3.8.1

    steps:
      - checkout

      - run:
          name: Install Pipenv
          command: sudo pip install pipenv

      - run:
          name: Install Python dependencies
          command: make install

      - run:
          name: Python security static analysis check
          command: make security-check

      - run:
          name: Python style check
          command: make style-check

      - run:
          name: Type-check with Mypy
          command: make type-check

      - run:
          name: Feature tests
          command: make test
