version: 2.1

jobs:

  build:

    docker:
      - image: circleci/python:3.7.4

    steps:
      - checkout

      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run: sudo pip install pipenv

      - run: make install

      - run: make test

      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
