version: 2.1

jobs:

  build:

    docker:
      - image: circleci/python:3.7.4

    steps:
      - checkout

      - run: sudo pip install pipenv

      - run: make install

      - run: flake8 --max-line-length=160

      - run: make test
